// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPictures.Data;

namespace UPictures.Data.Migrations
{
    [DbContext(typeof(UPicturesContext))]
    [Migration("20180715032735_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UPictures.Core.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CameraMaker")
                        .HasMaxLength(255);

                    b.Property<string>("CameraModel")
                        .HasMaxLength(255);

                    b.Property<DateTime>("DateTaken");

                    b.Property<string>("DirectoryName")
                        .HasMaxLength(5);

                    b.Property<string>("Extension")
                        .HasMaxLength(50);

                    b.Property<double>("FileSize");

                    b.Property<string>("Hash")
                        .HasMaxLength(32);

                    b.Property<int>("Height");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<string>("Path");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("Picture");
                });
#pragma warning restore 612, 618
        }
    }
}
